### ISSUE TITLE
404 Not Found in NC14

### ISSUE THREAD

**Issue by plyaskin** [NastuzziSamy/files_rightclick#31] opened 2018-10-26 13:31 UTC
Hi!
Not installed in NC14 through the app store.

Client error: \`GET https://cloud.nastuzzi.fr/s/HftfHyLXNNTYmNm/download` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><.body> <.h1>Not Found (truncated...)
![image](https://user-images.githubusercontent.com/9464550/47569512-004d0180-d95e-11e8-8526-d96644a72020.png)

**Comment by ari1105p** [comment] 2018-10-30 08:57
Unfortunately the same issue in NC 13.0.7 : Client error response [url] https://cloud.nastuzzi.fr/s/HftfHyLXNNTYmNm/download [status code] 404 [reason phrase] Not Found

**Comment by ilpssun** [comment] 2018-10-30 09:20
Duplicate of #30

**Comment by NastuzziSamy** [comment] 2018-10-30 10:03
I fixed the error btw, it is downloadable ;)

**Closed** 2018-10-30 10:02 UTC
Labels: duplicate, invalid

**Comment by ari1105p** [comment] 2018-10-30 10:12
Perfect! Thank you!
