### ISSUE TITLE
shifted Submenu

### ISSUE THREAD

**Issue by worldworm** [NastuzziSamy/files_rightclick#40] opened 2019-01-17 16:49 UTC
Depending on the scrolllocation of your windows, the submenu shifts away.

If you are all scrolled up -> everything works
![grafik](https://user-images.githubusercontent.com/13227454/51334216-a1d88080-1a7f-11e9-990e-ebe392fa8311.png)

If you scroll a bit down
![grafik](https://user-images.githubusercontent.com/13227454/51334264-c2083f80-1a7f-11e9-8e91-1d1722202a2e.png)

if you scroll a lot down
![grafik](https://user-images.githubusercontent.com/13227454/51334272-c7658a00-1a7f-11e9-88ca-c27c566806aa.png)

You have to scroll the page before you open the whole menu

Windows 7
NC 15.0.2
Firefox Quantum 61.0.2 (32-Bit)
Files Right Click 0.10.0

Thanks :)

**Comment by NastuzziSamy** [comment] 2019-01-17 18:57
Thank you for your feedback ! 😉

**Comment by NastuzziSamy** [comment] 2019-01-17 21:07
Do you still have that after hard reloading @worldworm ? I can't reproduce that

**Comment by worldworm** [comment] 2019-01-18 10:58
reloading everything didn't work. I also tried it in a freshly installed nextcloud with v0.10.1 & Internet Explorer. The same error.

**Comment by NastuzziSamy** [comment] 2019-01-18 13:04
@worldworm how do you produce that ? 
Do you see something on your console ?
Can you tell me what attributes your "body" tag have when you open the sub menu ? (Shift + right click to open the classic context menu)

**Comment by worldworm** [comment] 2019-01-18 14:30
My console logs the following warnings/infos:

`
Content Security Policy: Die Direktive child-src sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive worker-src zum Kontrollieren von Workern bzw. die Direktive frame-src zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
unreachable code after return statement[Weitere Informationen] merged.js:1566:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. merged.js:2176
New search handler registered search.js:67:4
querying Whats New data was successful: nocontent merged-template-prepend.js:4616:4
undefined merged-template-prepend.js:4617:4 
`

But i also get these on a fresh nextcloud without your plugin, so i think these aren't important

Body before opening the menu: 
height: auto; overflow: auto;
Body while opening the menu:
height: 100%; overflow: hidden;

**Comment by NastuzziSamy** [comment] 2019-01-18 14:38
Thank you for your feedback @worldworm.

Could you try that: 
- Right click, open the submenu, do not scroll.
- Check `body` has `height: 100%; overflow: hidden;` as style and apply it to the `html` tag
- Scroll to the infinite.

Tell me if it works better or if you have the same result, thanks

**Comment by NastuzziSamy** [comment] 2019-01-20 13:50
I did not understand the issue at the beggining, thank you, it is now fixed.

I am just releasing the v0.10.2, just check out ;)

**Closed** 2019-01-20 13:53 UTC
Labels: bug
